---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: website-ctr
          image: simbleau/website:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "1"
              memory: 512M
