---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  namespace: websites
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: website-ctr
          image: simbleau/website:construction
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "1"
              memory: 512M
