---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: simbleau/website:construction
          name: website-ctr
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "1"
              memory: 512M
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: website-svc
spec:
  ports:
    - port: 80
  selector:
    app: web
