---
- name: Installing zshrc
  ansible.builtin.copy:
    src: "zshrc"
    dest: "/Users/{{ lookup('env', 'USER') }}/.zshrc"
    mode: '0644'

- name: Installing zprofile
  ansible.builtin.copy:
    src: "zprofile"
    dest: "/Users/{{ lookup('env', 'USER') }}/.zprofile"
    mode: '0644'

- name: Load | Config (cddns)
  ansible.builtin.set_fact:
    cddns_toml: "{{ lookup('file', 'cddns.toml.sops.age') | community.sops.decrypt(output_type='binary') }}"

- name: Stage | Config (cddns)
  ansible.builtin.copy:
    content: "{{ cddns_toml }}\n"
    dest: "{{ lookup('env', 'HOME') }}/Library/Application Support/cddns/config.toml"
    owner: "{{ lookup('env', 'USER') }}"
    mode: 0400

- name: Load | Config (kubeconfig)
  ansible.builtin.set_fact:
    kubeconfig: "{{ lookup('file', 'kubeconfig.sops.age') | community.sops.decrypt(output_type='binary') }}"

- name: Stage | Config (kubeconfig)
  ansible.builtin.copy:
    content: "{{ kubeconfig }}\n"
    dest: "{{ lookup('env', 'HOME') }}/.kube/config"
    owner: "{{ lookup('env', 'USER') }}"
    mode: 0400
