---
- name: Set up users
  ansible.builtin.include_tasks: user.yml

- name: Copy keys
  ansible.builtin.include_tasks: keys.yml

- name: Install packages
  ansible.builtin.include_tasks: packages.yml

- name: Install configuration
  ansible.builtin.include_tasks: config.yml
