---
- name: Upgrade all system packages
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
  register: upgrade
  retries: 5
  until: upgrade is success

- name: Install GitHub CLI
  community.general.homebrew:
    name: gh
    state: present
  register: gh_cli
  retries: 5
  until: gh_cli is success

- name: Install | Kubectl
  community.general.homebrew:
    name: kubectl
    state: present
  register: kubectl
  retries: 5
  until: kubectl is success

# Install Rust
- name: Checking for Rust
  ansible.builtin.stat:
    path: "{{ lookup('env', 'HOME') }}/.cargo/bin/rustup"
  register: rustup
- name: Download Rust
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: "0755"
    force: true
  when: not rustup.stat.exists
- name: Install Rust
  ansible.builtin.command: /tmp/sh.rustup.rs -y
  when: not rustup.stat.exists

# cddns uses nightly, which can't be installed with community.general.cargo yet
# see: https://docs.ansible.com/ansible/latest/collections/community/general/cargo_module.html
# - name: Install cddns
#  community.general.cargo:
#    name: cddns

- name: Install Trunk
  community.general.cargo:
    name: trunk

# Install zsh completions
- name: Make zsh completions directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.zfunc"
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
    mode: 0755

- name: Check | Rustup completions
  ansible.builtin.stat:
    path: "{{ lookup('env', 'HOME') }}/.zfunc/rustup"
  register: cmp_rust

- name: Install | Rustup completions
  ansible.builtin.shell: rustup completions zsh > {{ lookup('env', 'HOME') }}/.zfunc/rustup
  when: not cmp_rust.stat.exists

- name: Check | Rustup completions
  ansible.builtin.stat:
    path: "{{ lookup('env', 'HOME') }}/.zfunc/cargo"
  register: cmp_cargo

- name: Install | Cargo completions
  ansible.builtin.shell: cargo completions zsh cargo > {{ lookup('env', 'HOME') }}/.zfunc/cargo
  when: not cmp_cargo.stat.exists

- name: Check | GitHub CLI completions
  ansible.builtin.stat:
    path: "{{ lookup('env', 'HOME') }}/.zfunc/gh"
  register: cmp_gh

- name: Install GitHub CLI completions
  ansible.builtin.shell: gh completion -s zsh > {{ lookup('env', 'HOME') }}/.zfunc/gh
  when: not cmp_gh.stat.exists

- name: Check | Kubectl completions
  ansible.builtin.stat:
    path: "{{ lookup('env', 'HOME') }}/.zfunc/kubectl"
  register: cmp_kubectl

- name: Install Kubectl completions
  ansible.builtin.shell: kubectl completion zsh > {{ lookup('env', 'HOME') }}/.zfunc/kubectl
  when: not cmp_kubectl.stat.exists
