---
- name: Provision System
  hosts: localhost
  connection: local
  become: false
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    # Install sops
    # TODO: Blocked on https://github.com/ansible-collections/community.sops/issues/128
    # - name: Install SOPS
    #  ansible.builtin.include_role:
    #    name: community.sops.install
    - name: Assert SOPS is installed
      delegate_to: localhost
      ansible.builtin.shell: command -v sops >/dev/null 2>&1
      register: is_sops_installed
      changed_when: is_sops_installed.rc != 0
      ignore_errors: false

    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5
  tasks:
    - name: Install Ubuntu
      ansible.builtin.include_role:
        name: ubuntu
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '22.04'

    - name: Install MacOS
      ansible.builtin.include_role:
        name: macos
      when: ansible_distribution == 'MacOSX'
