apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  labels:
    app: website
spec:
  replicas: 2
  selector:
    matchLabels:
      run: website-runner
  template:
    metadata:
      labels:
        run: website-runner
    spec:
      containers:
        - name: website
          image: simbleau/website:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
