apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Website
  - namespace.yml
  - service.yml
  - deployment.yml
  - ingress.yml
  # DDNS
  - ddns/deployment.yml
  - ddns/inventory.yml
  - ddns/secret.yml
namespace: website
