apiVersion: v1
entries:
  website:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2022-04-14T13:43:47.820442514-04:00"
    description: The kubernetes deployment for Spencer C. Imbleau's personal website.
    digest: c1768ab0b272e275aa9e5fe7ce0d77ff1c7252a7c4e3953ae063eddf115c39fc
    name: website
    type: application
    urls:
    - https://simbleau.github.io/k8s/helm-chart-packages/website-0.1.0.tgz
    version: 0.1.0
generated: "2022-04-14T13:43:47.819959974-04:00"
