---
- name: Reboot cluster
  hosts:
    - master
    - worker
  become: true
  gather_facts: false
  ignore_unreachable: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5
  tasks:
    - name: Rebooting odd nodes
      ansible.builtin.reboot:
        msg: Rebooting nodes
      when: inventory_hostname in groups['odd']

    - name: Pausing for 120 seconds...
      ansible.builtin.pause:
        seconds: 120

    - name: Rebooting even nodes
      ansible.builtin.reboot:
        msg: Rebooting nodes
      when: inventory_hostname in groups['even']

    - name: Pausing for 120 seconds...
      ansible.builtin.pause:
        seconds: 120

    - name: Rebooting master nodes individually
      throttle: 1
      ansible.builtin.reboot:
        msg: Rebooting nodes
      when: inventory_hostname in groups['master']
