
---
- hosts: all
  become: true
  gather_facts: false
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5
  tasks:
    - name: Reboot
      ansible.builtin.reboot:
        msg: Rebooting nodes