---
- name: Restart cluster
  hosts:
    - master
    - worker
  become: true
  gather_facts: true
  any_errors_fatal: true
  ignore_unreachable: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5
  tasks:
    - name: Restart Kubernetes
      ansible.builtin.include_role:
        name: xanmanning.k3s
        public: true
      vars:
        k3s_state: restarted
        k3s_become: true
