---
- hosts:
    - master
    - worker
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Assert SOPS is installed
      delegate_to: localhost
      shell: command -v sops >/dev/null 2>&1
      register: is_sops_installed
      ignore_errors: no

    - name: Pausing for 5 seconds...
      pause:
        seconds: 5
  tasks:
    - name: Install Kubernetes
      ansible.builtin.include_role:
        name: xanmanning.k3s
        public: true
      vars:
        k3s_state: restarted
        k3s_become: true
