---
- name: System upgrade for cluster
  hosts:
    - master
    - worker
  become: true
  gather_facts: true
  any_errors_fatal: true
  ignore_unreachable: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5
  tasks:
    - name: Cache update
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      register: apt_update
      retries: 3
      until: apt_update is success

    - name: Full upgrade
      ansible.builtin.apt:
        upgrade: full
        autoclean: true
        autoremove: true
      register: apt_upgrade
      retries: 5
      until: apt_upgrade is success
