# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddns-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cddns
  template:
    metadata:
      labels:
        app: cddns
    spec:
      volumes: # Expose inventory as volume
        - name: "inventory"
          configMap:
            name: "cddns-inventory"
      containers:
        - name: cddns
          image: simbleau/cddns:latest
          volumeMounts:
            - name: inventory # Mount inventory file
              mountPath: /opt/etc/cddns/
              readOnly: true
          env:
            - name: CDDNS_INVENTORY_PATH
              value: /opt/etc/cddns/inventory
            - name: CDDNS_VERIFY_TOKEN
              valueFrom: # Cloudflare API token
                secretKeyRef:
                  name: cddns-api-token
                  key: token
