# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddns-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: cddns
  template:
    metadata:
      labels:
        app: cddns
    spec:
      volumes: # Expose inventory as volume
        - name: "inventory"
          configMap:
            name: "cddns-inventory"
      containers:
        - name: cddns
          image: simbleau/cddns:v0.2.3
          imagePullPolicy: Always
          volumeMounts:
            - name: inventory # Mount inventory file
              mountPath: /opt/etc/cddns/
              readOnly: true
          env:
            - name: CDDNS_INVENTORY_PATH
              value: /opt/etc/cddns/inventory
            - name: CDDNS_VERIFY_TOKEN
              valueFrom: # Cloudflare API token
                secretKeyRef:
                  name: cddns-api-token
                  key: token
          readinessProbe:
            exec:
              command:
                - cddns verify
            # Start readyness checks after 10s
            initialDelaySeconds: 10
            # 5 min to startup (30 * 10 = 300s)
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - cddns verify
            initialDelaySeconds: 10
            failureThreshold: 1
            periodSeconds: 10
