---
- hosts:
    - workstations
  become: true
  become_method: su
  become_user: provision
  gather_facts: false
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      pause:
        seconds: 5
  roles:
    - ubuntu
