# Set PATH, MANPATH, etc., for Homebrew.
eval "$(/opt/homebrew/bin/brew shellenv)"
# Additional pathing
export PATH="$PATH:$HOME/Applications"
export PATH="$PATH:/Library/TeX/texbin"
export PATH="$PATH:$HOME/Library/Python/3.9/bin"

# Automatically add SSH keys
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa

# Source cargo
source "$HOME/.cargo/env" || true

# Source Docker Desktop
source "$HOME/.docker/init-zsh.sh" || true