apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes: # Expose data as volume
        - name: "pgdata"
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: pgdata
              mountPath: /pool/rgx/data/login
              readOnly: false
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_USER
              value: test
            - name: POSTGRES_PASSWORD
              value: test
