apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes: # Expose data as volume
        - name: "pgdata"
          persistentVolumeClaim:
            claimName: postgresql-pv-claim
      containers:
        - name: postgres
          image: postgres
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data/pgdata
          env:
            - name: POSTGRES_USER
              value: test
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: token
          resources:
            limits:
              memory: 128Mi
              cpu: "0.5"
            requests:
              memory: 32Mi
              cpu: "0.1"
