---
- include_vars: config.yml

- name: Create configuration directory
  ansible.builtin.file:
    path: "{{ config_dir }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0775

# .bashrc
- name: Installing bashrc
  ansible.builtin.copy:
    src: ".bashrc"
    dest: "{{ home_dir }}/.bashrc"
