name: Schedule - Renovate

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main
    paths:
      - ".github/renovate.json"
      - ".github/renovate/**.json"

env:
  RENOVATE_CONFIG_FILE: .github/renovate.json

jobs:
  renovate:
    name: Verify Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Verify Renovate Configuration
        uses: tj-actions/renovate-config-validator@v1.3
        with:
          config-file: "${{ env.RENOVATE_CONFIG_FILE }}"
