apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # General
  - namespace.yml
  # Website
  - website/deployment.yml
  - website/service.yml
  - website/ingress.yml
  # DDNS
  - ddns/deployment.yml
  - ddns/inventory.yml
  - ddns/secret.yml
namespace: website
